# Generated by Django 5.0.6 on 2024-05-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
